### ISSUE TITLE
Really great example !

### ISSUE THREAD

**Issue by isatahiri** [jjcolumb/XAF-blazor-change-connection-to-the-database-at-runtime#1]
Bravo to you both guys ! 
! Assuming that we use this for 3-5 difference customers (1 point of entry for 3-5 customers). Would that be easily possible ?

**Comment by jjcolumb** [comment]
This should work for as many customers as you have. Just make sure to add those databases here: 
public const string Databases = "Select DB;E1344_DB1_Blazor;E1344_DB2_Blazor";

**Comment by jjcolumb** [comment]
@isatahiri let me know if you run into any issue
